### ISSUE TITLE
Question sur les opérateurs unaires

### ISSUE THREAD

**Issue by felixSabatie** [PolytechLyon/isi3-tp2-visiteur-sabatie-tp2#1]
Sur l'exemple du TP suivant, le parcours infixe est sensé donner "1+2×3+(−4)". Cependant les opérateurs unaires ont seulement un fils gauche, du coup le parcours infixe produit "1+2×3+4-", puisque le 4 est le fils gauche et qu'il est donc parcouru en premier. Pour être cohérent avec l'exemple, les opérateurs unaires ne devraient-ils pas plutôt avoir seulement un fils droit ?

![image](https://user-images.githubusercontent.com/22494541/37253197-b5620f50-252e-11e8-8283-74e5383c6706.png)

**Comment by Slashgear** [comment]
Si cela te semble plus logique. Do IT ! 😄
