### ISSUE TITLE
Need codereview

### ISSUE THREAD

**Issue by felixSabatie** [PolytechLyon/isi3-tp2-visiteur-sabatie-tp2#2]
Bonjour, je suis prêt à avoir un retour sur mon code !

**Comment by Slashgear** [comment]
- C'est pas trop mal, le rapport est bien

- Peux tu me dire ici quel est le use case du pattern visteur ?

- La priorité sous forme de booléen c'est pas cool. Une priorité au sens mathématique c'est pas vrai ou faux. C'est assez dangereux de représenter des choses qui ne sont pas vrai/faux par des booléen.
Il faudrait soit:
   - passer par un ENUM de Priorité
   - passer par un type

- Regarde un peu les Optional en java, tu as pas mal de méthode utiles (orElse, ifPresent, map), ça pourrait te servir ici.

- Un rangement en package (nom de package en minuscule)

**Comment by felixSabatie** [comment]
J'ai fait les modifications, j'ai pas vraiment réussi à mieux utiliser les méthodes des Optional que ce que j'avais déjà fait par contre

**Comment by Slashgear** [comment]
Je ne trouve pas ton explication du use case du pattern visiteur ❓

**Comment by felixSabatie** [comment]
J'ai mis l'explication dans la question 1 :

> Le pattern Visiteur est ici intéressant car disposons de plusieurs classes très différentes regroupées sous l'interface noeuds.Noeud, et que nous souhaitons faire des opérations sur ces classes de plusieurs manières différentes. Chaque type d'opération aura donc sa propre classe Visiteur, et on pourra effectuer des opérations différentes selon le type d'objet visité.

**Comment by Slashgear** [comment]
Ok, c'est presque ça.

Je te link le use case exact http://java-design-patterns.com/patterns/visitor/

C'est pas mal.
